#!/bin/bash
USERPATH="$PWD"
if [ "$1" == "build" ]; then
 if [ -z "$2" ]; then
 echo "ERROR : input file missing!"
 echo "writing example:  slang inputfile.sl outputfile"
 exit 1
 else
 echo "compiling..."
 node "$(cd "$(dirname "$0")" && pwd)/std/compiler.js" "$USERPATH/$2" "$USERPATH/$3" "$4"
 fi
elif [ "$1" == "run" ]; then
 echo "compiling..."
 node "$(cd "$(dirname "$0")" && pwd)/std/compiler.js" "$USERPATH/$2" "$USERPATH/$3" "$4"
 ./"$3"
elif [ "$1" == "install" ]; then
 cd "$PREFIX/slang/libs"
 git clone "$2"
 cd "$USERPATH"
fi
